# Generated by Django 4.2.2 on 2023-07-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='company_owner',
            field=models.BooleanField(default=False, verbose_name='Dono de alguma companhia?'),
        ),
        migrations.AddField(
            model_name='users',
            name='library_owner',
            field=models.BooleanField(default=False, verbose_name='Dono de alguma biblioteca?'),
        ),
    ]
