# Generated by Django 4.2.2 on 2023-12-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_type_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='type_user',
            field=models.CharField(choices=[('default', 'Padrão'), ('owner', 'Dono'), ('admin', 'Admin')], default='default', max_length=100, verbose_name='Tipo do usuário'),
        ),
    ]
