# Generated by Django 4.2.2 on 2023-12-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUsibras', '0024_companys_logo'),
        ('users', '0006_users_favorite_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='favorite_books',
            field=models.ManyToManyField(blank=True, related_name='user_favorite_books', to='adminUsibras.books', verbose_name='Livros Favoritos'),
        ),
    ]
