# Generated by Django 4.2.2 on 2023-12-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0011_librarys_type_payments_accepted'),
        ('users', '0007_alter_users_favorite_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='favorite_libraries',
            field=models.ManyToManyField(blank=True, related_name='user_favorite_libraries', to='library.librarys', verbose_name='Bibliotecas Favoritas'),
        ),
    ]
