# Generated by Django 4.2.2 on 2024-01-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_users_favorite_libraries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='type_user',
            field=models.CharField(choices=[('client', 'Cliente'), ('employee', 'Funcionário'), ('owner', 'Dono'), ('admin', 'Admin')], default='client', max_length=100, verbose_name='Tipo do usuário'),
        ),
    ]
