# Generated by Django 4.2.1 on 2023-06-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUsibras', '0005_remove_books_author_books_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='state',
            field=models.CharField(choices=[('new', 'Novo'), ('semi-new', 'Semi-novo'), ('used', 'Usado')], default='new', max_length=50, verbose_name='Estado'),
        ),
    ]
