# Generated by Django 4.2.1 on 2023-06-11 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminUsibras', '0006_alter_books_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='book_genre',
            field=models.CharField(choices=[('mistery', 'Mistério'), ('comedy', 'Comédia'), ('romance', 'Romance'), ('terror', 'Terror')], default='', max_length=50, verbose_name='Genero do livro'),
        ),
        migrations.AlterField(
            model_name='books',
            name='publishing_company',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='adminUsibras.companys', verbose_name='Publicado pela empresa'),
        ),
    ]
