# Generated by Django 4.2.1 on 2023-06-11 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminUsibras', '0007_companys_books_book_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='publishing_company',
            field=models.ForeignKey(default='', max_length=255, on_delete=django.db.models.deletion.CASCADE, to='adminUsibras.companys', verbose_name='Publicado pela empresa'),
        ),
    ]
