# Generated by Django 4.2.1 on 2023-06-11 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminUsibras', '0008_alter_books_publishing_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='publishing_company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminUsibras.companys', verbose_name='Publicado pela empresa'),
        ),
    ]
