# Generated by Django 4.2.1 on 2023-06-11 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminUsibras', '0009_alter_books_publishing_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companys',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
    ]
