# Generated by Django 4.2.1 on 2023-06-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUsibras', '0011_companys_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='create_at',
            field=models.DateField(blank=True, null=True, verbose_name='Data de criação'),
        ),
    ]
