# Generated by Django 4.2.1 on 2023-06-11 01:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminUsibras', '0012_alter_books_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='companys',
            name='owner',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Dono(s)'),
        ),
    ]
