# Generated by Django 4.2.2 on 2023-08-31 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUsibras', '0013_companys_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='Em estoque'),
        ),
    ]
