# Generated by Django 4.2.2 on 2023-11-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUsibras', '0014_books_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.FloatField(default=1, verbose_name='Preço'),
            preserve_default=False,
        ),
    ]
