# Generated by Django 4.2.2 on 2023-11-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUsibras', '0015_books_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='companys',
            name='cep',
            field=models.CharField(default=1, max_length=14, verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companys',
            name='complement',
            field=models.CharField(blank=True, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='companys',
            name='number',
            field=models.CharField(default=1, verbose_name='Número'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companys',
            name='reference_point',
            field=models.CharField(default=1, verbose_name='Ponto de referência'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companys',
            name='state',
            field=models.CharField(default=1, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companys',
            name='street',
            field=models.CharField(default=1, verbose_name='Rua'),
            preserve_default=False,
        ),
    ]
