# Generated by Django 4.2.2 on 2023-11-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUsibras', '0016_companys_cep_companys_complement_companys_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companys',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companys',
            name='phone',
            field=models.CharField(default=1, verbose_name='Telefone'),
            preserve_default=False,
        ),
    ]
