# Generated by Django 4.2.2 on 2023-11-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUsibras', '0018_alter_companys_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_genre', models.CharField(verbose_name='Gênero')),
            ],
            options={
                'verbose_name': 'Gênero do Livro',
                'verbose_name_plural': 'Gênero dos Livros',
            },
        ),
        migrations.RemoveField(
            model_name='books',
            name='book_genre',
        ),
        migrations.AddField(
            model_name='books',
            name='book_genre',
            field=models.ManyToManyField(related_name='books_genre', to='adminUsibras.bookgenres', verbose_name='Gênero do livro'),
        ),
    ]
