# Generated by Django 4.2.2 on 2023-12-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUsibras', '0019_bookgenres_remove_books_book_genre_books_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_cover',
            field=models.ImageField(default=1, upload_to='', verbose_name='Capa do livro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='synopsis',
            field=models.TextField(default='', verbose_name='Sinpose'),
        ),
    ]
