# Generated by Django 4.2.2 on 2023-12-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUsibras', '0020_books_book_cover_books_synopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='synopsis',
            field=models.TextField(default='', verbose_name='Sinopse'),
        ),
    ]
