# Generated by Django 4.2.2 on 2023-12-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0009_remove_librarys_owner_library_librarys_owner_library'),
        ('adminUsibras', '0021_alter_books_synopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='available_in_libraries',
            field=models.ManyToManyField(related_name='book_available_libraries', to='library.librarys', verbose_name='Disponível nas bibliotecas'),
        ),
    ]
