# Generated by Django 4.2.2 on 2023-12-07 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0009_remove_librarys_owner_library_librarys_owner_library'),
        ('adminUsibras', '0022_books_available_in_libraries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='available_in_libraries',
        ),
        migrations.AddField(
            model_name='books',
            name='available_in_libraries',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='book_available_libraries', to='library.librarys', verbose_name='Disponível na biblioteca'),
            preserve_default=False,
        ),
    ]
