# Generated by Django 4.2.2 on 2023-12-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUsibras', '0023_remove_books_available_in_libraries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companys',
            name='logo',
            field=models.ImageField(default=1, upload_to='', verbose_name='Logo'),
            preserve_default=False,
        ),
    ]
