# Generated by Django 4.2.2 on 2023-09-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Nome')),
                ('developed_by', models.CharField(max_length=150, verbose_name='Desenvolvido por:')),
                ('description', models.TextField(max_length=255, verbose_name='Descrição')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email para contato:')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefone para contato:')),
            ],
            options={
                'verbose_name': 'Sobre nós',
                'verbose_name_plural': 'Sobre nós',
            },
        ),
        migrations.CreateModel(
            name='TermsOfUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_of_use', models.FileField(upload_to='terms_of_use', verbose_name='Termos de Uso')),
            ],
        ),
    ]
