# Generated by Django 4.2.2 on 2023-09-05 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termsofuse',
            options={'verbose_name': 'Termo de Uso', 'verbose_name_plural': 'Termos de Uso'},
        ),
    ]
