# Generated by Django 4.2.2 on 2023-09-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_alter_termsofuse_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsofuse',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Titulo'),
        ),
    ]
