# Generated by Django 4.2.2 on 2023-11-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0003_termsofuse_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsofuse',
            name='privacy_police',
            field=models.FileField(default=1, upload_to='privacy_police', verbose_name='Política de privacidade'),
            preserve_default=False,
        ),
    ]
