# Generated by Django 4.2.2 on 2023-11-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0004_termsofuse_privacy_police'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_police', models.FileField(upload_to='privacy_police', verbose_name='Política de privacidade')),
            ],
            options={
                'verbose_name': 'Política de Privacidade',
                'verbose_name_plural': 'Políticas de Privacidade',
            },
        ),
        migrations.RemoveField(
            model_name='termsofuse',
            name='privacy_police',
        ),
    ]
