# Generated by Django 4.2.2 on 2023-07-28 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminUsibras', '0013_companys_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksPurchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Data da compra')),
                ('books', models.ManyToManyField(to='adminUsibras.books', verbose_name='Livros comprados')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_book_purchase', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Livro comprado',
                'verbose_name_plural': 'Livros comprados',
            },
        ),
    ]
