# Generated by Django 4.2.2 on 2023-07-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookspurchases',
            name='date',
            field=models.DateTimeField(auto_created=True, verbose_name='Data da compra'),
        ),
    ]
