# Generated by Django 4.2.2 on 2023-07-28 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_bookspurchases_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookspurchases',
            options={'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
    ]
