# Generated by Django 4.2.2 on 2023-11-16 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0001_initial'),
        ('purchases', '0003_alter_bookspurchases_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookspurchases',
            name='type_payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='payment_methods.paymentmethods', verbose_name='Tipo de pagamento'),
            preserve_default=False,
        ),
    ]
