# Generated by Django 4.2.2 on 2023-12-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_bookspurchases_type_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookspurchases',
            name='came_via_ad',
            field=models.BooleanField(default=False, verbose_name='Veio atráves do anúncio do livro'),
        ),
    ]
