# Generated by Django 4.2.2 on 2023-12-23 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertsViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, verbose_name='Data de visualização')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_viewed', to='adverts.adverts', verbose_name='Anúncio visto')),
                ('user_viewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_viewed_advert', to=settings.AUTH_USER_MODEL, verbose_name='Visto pelo usuário')),
            ],
        ),
    ]
