# Generated by Django 4.2.2 on 2023-12-23 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_advertsviewed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertsviewed',
            options={'verbose_name': 'Anúncio visualizado', 'verbose_name_plural': 'Anúncios visualizados'},
        ),
    ]
