# Generated by Django 4.2.2 on 2023-12-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0003_alter_advertsviewed_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertsviewed',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de visualização'),
        ),
    ]
