# Generated by Django 4.2.2 on 2023-12-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0004_alter_advertsviewed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertsviewed',
            name='description',
            field=models.CharField(default=1, max_length=100, verbose_name='Descrição do anúncio'),
            preserve_default=False,
        ),
    ]
