# Generated by Django 4.2.2 on 2023-12-23 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0005_advertsviewed_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertsviewed',
            name='description',
        ),
    ]
