# Generated by Django 4.2.2 on 2023-12-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0006_remove_advertsviewed_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='adverts',
            name='description',
            field=models.TextField(default='', max_length=320, verbose_name='Descrição do anúncio'),
        ),
    ]
