# Generated by Django 4.2.2 on 2023-12-25 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminUsibras', '0024_companys_logo'),
        ('adverts', '0007_adverts_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertsBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.ImageField(upload_to='', verbose_name='Anúncio')),
                ('description', models.TextField(default='', max_length=320, verbose_name='Descrição do Anúncio')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('expiration', models.DateTimeField(auto_now_add=True, verbose_name='Expira em')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminUsibras.books', verbose_name='Anúncio do Livro')),
            ],
            options={
                'verbose_name': 'Anúncio de Livros',
                'verbose_name_plural': 'Anúncios de Livros',
            },
        ),
    ]
