# Generated by Django 4.2.2 on 2023-12-25 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0008_advertsbooks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertsviewed',
            options={'verbose_name': 'Anúncio Visualizado', 'verbose_name_plural': 'Anúncios Visualizados'},
        ),
    ]
