# Generated by Django 4.2.2 on 2023-12-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0009_alter_advertsviewed_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertsbooks',
            name='create_at',
            field=models.DateTimeField(verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='advertsbooks',
            name='expiration',
            field=models.DateTimeField(verbose_name='Expira em'),
        ),
    ]
