# Generated by Django 4.2.2 on 2024-01-03 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adverts', '0010_alter_advertsbooks_create_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertsBookViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data da visualização')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advert_book_viewed', to='adverts.advertsbooks', verbose_name='Anúncio visualizado')),
                ('user_viewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_viewed_book_advert', to=settings.AUTH_USER_MODEL, verbose_name='Visualizado pelo usuário')),
            ],
        ),
    ]
