# Generated by Django 4.2.2 on 2024-01-03 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0011_advertsbookviewed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertsbookviewed',
            options={'verbose_name': 'Anúncio de Livro Visualizado', 'verbose_name_plural': 'Anúncios de Livros Visualizados'},
        ),
    ]
